---

- name: Clone the kernel tree
  git:
    repo: "{{ kernel_repo }}"
    dest: kernel/
    version: master
    clone: yes
    depth: 5
  retries: 3
  delay: 5
  register: result
  until: result | success

- name: Retrieve the latest Fedora kernel config file
  get_url:
    url: https://src.fedoraproject.org/cgit/rpms/kernel.git/plain/kernel-x86_64.config
    dest: kernel/.config
  retries: 3
  delay: 5
  register: result
  until: result | success

- name: Update the kernel config with any missing defaults
  command: make -C kernel/ olddefconfig
  register: update_config

- name: Print stderr from config update
  debug:
    var: update_config.stderr

- name: Get ccache stats
  command: ccache -s
  register: ccache_before_stats
  environment:
    CCACHE_DIR: /opt/ccache/

- name: Print ccache stats
  debug:
    var: ccache_before_stats.stdout

- name: Compile the kernel
  command: "make -j{{ ansible_processor_vcpus }} -C kernel/ {{ kernel_build_target }}"
  register: kernel_compile
  environment:
    CCACHE_DIR: /opt/ccache/
    PATH: "/usr/lib64/ccache:{{ ansible_env.PATH }}"

- name: Print stderr from kernel build
  debug:
    var: kernel_compile.stderr

- name: Get ccache stats
  command: ccache -s
  register: ccache_after_stats
  environment:
    CCACHE_DIR: /opt/ccache/

- name: Print ccache stats
  debug:
    var: ccache_after_stats.stdout
