---

- name: Clone the kernel tree
  git:
    repo: "{{ kernel_repo }}"
    dest: kernel/
    version: master
    clone: yes
    depth: 5

- name: Retrieve the latest Fedora kernel config file
  get_url:
    url: https://src.fedoraproject.org/cgit/rpms/kernel.git/plain/kernel-x86_64.config
    dest: kernel/.config

- name: Update the kernel config with any missing defaults
  command: make -C kernel/ olddefconfig
  register: update_config

- name: Print stderr from config update
  debug:
    var: update_config.stderr

- name: Compile the kernel
  command: "make -j{{ ansible_processor_vcpus }} -C kernel/ tarxz-pkg"
  register: kernel_compile

- name: Print stderr from kernel build
  debug:
    var: kernel_compile.stderr
